'use strict'

module.exports = {
  WORLDPAY_ENVIRONMENTS: {
    test: 'https://secure-test.worldpay.com/jsp/merchant/xml/paymentService.jsp',
    production: 'https://secure.worldpay.com/jsp/merchant/xml/paymentService.jsp',
  },
  WORLDPAY_PSP_IDENTIFIER: 'worldpay',

  WORLDPAY_DTD_PUB: '-//Worldpay//DTD Worldpay PaymentService v1//EN',
  WORLDPAY_DTD_SYS: 'http://dtd.worldpay.com/paymentService_v1.dtd',
  WORLDPAY_DTD_VERSION: 1.4,

  WORLDPAY_ORDER_CAPTURE_DELAY_AUTOMATIC: 0,
  WORLDPAY_ORDER_CAPTURE_DELAY_DEFAULT: 'DEFAULT',
  WORLDPAY_ORDER_CAPTURE_DELAY_OFF: 'OFF',

  WORLDPAY_PAYMENT_METHOD_MASK_ALL: 'ALL',
  WORLDPAY_PAYMENT_METHOD_MASK_ONLINE: 'ONLINE',

  WORLDPAY_AUTHENTICATION_METHOD_GUEST_CHECKOUT: 'guestCheckout',
  WORLDPAY_AUTHENTICATION_METHOD_LOCAL_ACCOUNT: 'localAccount',
  WORLDPAY_AUTHENTICATION_METHOD_FEDERATED_ACCOUNT: 'federatedAccount',
  WORLDPAY_AUTHENTICATION_METHOD_ISSUER_CREDENTIALS: 'issuerCredentials',
  WORLDPAY_AUTHENTICATION_METHOD_THIRD_PARTY: 'thirdPartyAuthentication',
  WORLDPAY_AUTHENTICATION_METHOD_FIDO_AUTHENTICATOR: 'fidoAuthenticator',

  WORLDPAY_ACCOUNT_INDICATOR_NO_ACCOUNT: 'noAccount',
  WORLDPAY_ACCOUNT_INDICATOR_NO_CHANGE: 'noChange',
  WORLDPAY_ACCOUNT_INDICATOR_CHANGED_DURING_TRANSACTION: 'changedDuringTransaction',
  WORLDPAY_ACCOUNT_INDICATOR_CREATED_DURING_TRANSACTION: 'createdDuringTransaction',
  WORLDPAY_ACCOUNT_INDICATOR_DURING_TRANSACTION: 'duringTransaction',
  WORLDPAY_ACCOUNT_INDICATOR_THIS_TRANSACTION: 'thisTransaction',
  WORLDPAY_ACCOUNT_INDICATOR_LESS_THAN_THIRTY_DAYS: 'lessThanThirtyDays',
  WORLDPAY_ACCOUNT_INDICATOR_LESS_THIRTY_TO_SIXTY_DAYS: 'thirtyToSixtyDays',
  WORLDPAY_ACCOUNT_INDICATOR_MORE_THAN_SIXTY_DAYS: 'moreThanSixtyDays',

  WORLDPAY_SHIPPING_METHOD_SHIP_TO_BILLING_ADDRESS: 'shipToBillingAddress',
  WORLDPAY_SHIPPING_METHOD_SHIP_TO_VERIFIED_ADDRES: 'shipToVerifiedAddress',
  WORLDPAY_SHIPPING_METHOD_SHIP_TO_OTHER_ADDRESS: 'shipToOtherAddress',
  WORLDPAY_SHIPPING_METHOD_SHIP_TO_STORE: 'shipToStore',
  WORLDPAY_SHIPPING_METHOD_DIGITAL: 'digital',
  WORLDPAY_SHIPPING_METHOD_UNSHIPPED_TRAVEL_OR_EVENT_TICKETS: 'unshippedTravelOrEventTickets',
  WORLDPAY_SHIPPING_METHOD_OTHER: 'other',

  WORLDPAY_DELIVERY_TIMEFRAME_ELECTRONIC_DELIVERY: 'electronicDelivery',
  WORLDPAY_DELIVERY_TIMEFRAME_SAME_DAY_SHIPPING: 'sameDayShipping',
  WORLDPAY_DELIVERY_TIMEFRAME_OVERNIGHT_SHIPPING: 'overnightShipping',
  WORLDPAY_DELIVERY_TIMEFRAME_OTHER_SHIPPING: 'otherShipping',

  WORLDPAY_NOTIFICATION_TYPES: {
    AUTHORISED: 'AUTHORISED',
    CANCELLED: 'CANCELLED',
    CAPTURED: 'CAPTURED',
    SETTLED: 'SETTLED',
    SETTLED_BY_MERCHANT: 'SETTLED_BY_MERCHANT',
    REFUSED: 'REFUSED',
    SENT_FOR_REFUND: 'SENT_FOR_REFUND',
    REFUNDED: 'REFUNDED',
    REFUNDED_BY_MERCHANT: 'REFUNDED_BY_MERCHANT',
    SENT_FOR_AUTHORISATION: 'SENT_FOR_AUTHORISATION',
    ERROR: 'ERROR',
    EXPIRED: 'EXPIRED',
    REFUND_FAILED: 'REFUND_FAILED',
    CAPTURE_FAILED: 'CAPTURE_FAILED',
    SHOPPER_CANCELLED: 'SHOPPER_CANCELLED',
    SHOPPER_REDIRECTED: 'SHOPPER_REDIRECTED',
    REFUND_WEBFORM_ISSUED: 'REFUND_WEBFORM_ISSUED',
    CHARGED_BACK: 'CHARGED_BACK',
  },

  WORLDPAY_JOURNAL_TYPES: {
    SENT_FOR_AUTHORISATION: 'SENT_FOR_AUTHORISATION',
    AUTHORISED: 'AUTHORISED',
    CAPTURED: 'CAPTURED',
    SENT_FOR_REFUND: 'SENT_FOR_REFUND',
    REFUNDED: 'REFUNDED',
    SETTLED: 'SETTLED',
    CANCELLED: 'CANCELLED',
  },

  WORLDPAY_JOURNAL_STATUS: {
    IN_PROCESS_AUTHORISED: 'IN_PROCESS_AUTHORISED',
    IN_PROCESS_CAPTURED: 'IN_PROCESS_CAPTURED',
    SETTLED_BIBIT_NET: 'SETTLED_BIBIT_NET',
  },
}
